In [32]:
import pandas as pd

In [33]:
df = pd.read_excel("Assignment_TrainingData.xlsx")

In [34]:
df.head()

,focal_addr,focal_addr_type,blacklist,last_ts,tot_txn,tot_val,min_val,max_val,sd2_val,unq_other_addr,days_diff_first_last,contract_creation,recv_txn,tot_val_recv,min_val_recv,max_val_recv,avg_val_recv,sd2_val_recv,unq_from_addr,days_diff_first_last_recv,sent_txn,tot_val_sent,min_val_sent,max_val_sent,avg_val_sent,sd2_val_sent,unq_to_addr,days_diff_first_last_sent,to_contract_txn,tot_val_to_contract,min_val_to_contract,max_val_to_contract,avg_val_to_contract,erc20_txn,sum_val_erc20,erc721_txn,sum_val_erc721
0,0x00000002de4e35b0838fe97e09bb26317c2e570c,contract address,0.0,2023-01-29 21:43:23,402.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,70.540139,0.0,402.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,70.540139,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,0x0000000506063a51c6ce59906d8c40f7d7fe92a7,wallet address,1.0,2023-02-15 15:53:59,16.0,1.843963e+19,0.000000e+00,1.800000e+19,1.892915e+37,13.0,153.244306,16.0,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,16.0,1.843963e+19,0.000000e+00,1.800000e+19,1.152477e+18,1.892915e+37,13.0,153.244306,10.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,3.0,0.000000e+00,0.0,NaN
2,0x0000098a312e1244f313f83cac319603a97f4582,wallet address,1.0,2023-02-08 12:19:59,8792.0,1.500201e+19,0.000000e+00,1.000000e+18,1.703185e+33,1486.0,103.834028,8792.0,17.0,1.500000e+19,1.000000e+10,1.000000e+18,8.823529e+17,1.038062e+35,3.0,70.376528,8775.0,2.010000e+15,0.000000e+00,1.000000e+15,2.290598e+11,2.278792e+26,1483.0,103.834028,8493.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,1356.0,0.000000e+00,4225.0,0.000000e+00
3,0x000677bbab0fea85506f5f63806d331c9c2df1ac,wallet address,0.0,2022-08-21 09:26:43,1.0,7.287733e+14,7.287733e+14,7.287733e+14,0.000000e+00,1.0,0.000000,0.0,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,1.0,7.287733e+14,7.287733e+14,7.287733e+14,7.287733e+14,0.000000e+00,1.0,0.000000,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,0x000f4432a40560bbff1b581a8b7aded8dab80026,wallet address,1.0,2023-02-15 01:53:11,247.0,4.243310e+19,0.000000e+00,8.200000e+18,5.954650e+35,91.0,179.527037,247.0,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,247.0,4.243310e+19,0.000000e+00,8.200000e+18,1.717939e+17,5.954650e+35,91.0,179.527037,215.0,2.880170e+19,0.0,8.200000e+18,1.339614e+17,30.0,1.045000e+19,17.0,5.500000e+17

### Lets check when was the first and last transactions

In [37]:
df.last_ts.min()

Timestamp('2022-08-16 00:55:38')

In [38]:
df.last_ts.max()

Timestamp('2023-02-15 23:55:35')

# Lets change the datetime column last_ts to integer

## Considering we are calculating the last transaction from 16th of February 2023, lets calculate the number of days since the last transaction

In [50]:
# specify date
specified_date = pd.Timestamp('2023-02-16')

# calculate difference in days
df['days_since_last_txn'] = (specified_date - df['last_ts']).dt.days

### Dataframe consists of 6280 rows of addresses with transactions with 37 columns

In [51]:
df.loc[df.days_since_last_txn == df.days_since_last_txn.min()]

,focal_addr,focal_addr_type,blacklist,last_ts,tot_txn,tot_val,min_val,max_val,sd2_val,unq_other_addr,days_diff_first_last,contract_creation,recv_txn,tot_val_recv,min_val_recv,max_val_recv,avg_val_recv,sd2_val_recv,unq_from_addr,days_diff_first_last_recv,sent_txn,tot_val_sent,min_val_sent,max_val_sent,avg_val_sent,sd2_val_sent,unq_to_addr,days_diff_first_last_sent,to_contract_txn,tot_val_to_contract,min_val_to_contract,max_val_to_contract,avg_val_to_contract,erc20_txn,sum_val_erc20,erc721_txn,sum_val_erc721,days_since_last_txn
1,0x0000000506063a51c6ce59906d8c40f7d7fe92a7,wallet address,1.0,2023-02-15 15:53:59,16.0,1.843963e+19,0.000000e+00,1.800000e+19,1.892915e+37,13.0,153.244306,16.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,16.0,1.843963e+19,0.000000e+00,1.800000e+19,1.152477e+18,1.892915e+37,13.0,153.244306,10.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,3.0,0.000000e+00,0.0,NaN,0
4,0x000f4432a40560bbff1b581a8b7aded8dab80026,wallet address,1.0,2023-02-15 01:53:11,247.0,4.243310e+19,0.000000e+00,8.200000e+18,5.954650e+35,91.0,179.527037,247.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,247.0,4.243310e+19,0.000000e+00,8.200000e+18,1.717939e+17,5.954650e+35,91.0,179.527037,215.0,2.880170e+19,0.0,8.200000e+18,1.339614e+17,30.0,1.045000e+19,17.0,5.500000e+17,0
53,0x01e060498c74141ec7454c6b8cc670dd1a99a2dc,wallet address,1.0,2023-02-15 14:35:47,82.0,1.383000e+20,0.000000e+00,3.200000e+19,3.075409e+37,26.0,176.023924,82.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,82.0,1.383000e+20,0.000000e+00,3.200000e+19,1.686585e+18,3.075409e+37,26.0,176.023924,78.0,1.113000e+20,0.0,3.200000e+19,1.426923e+18,26.0,1.500000e+19,0.0,NaN,0
94,0x03e3e6b16177aa6880b381c4e029b563857880a2,wallet address,0.0,2023-02-15 08:52:35,1.0,2.000000e+16,2.000000e+16,2.000000e+16,0.000000e+00,1.0,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,1.0,2.000000e+16,2.000000e+16,2.000000e+16,2.000000e+16,0.000000e+00,1.0,0.000000,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0
95,0x0405049ea3757f60a43a4bdfdedf498034841fac,wallet address,1.0,2023-02-15 15:14:35,202.0,1.100069e+21,0.000000e+00,1.190000e+20,2.642339e+38,79.0,179.917870,202.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,202.0,1.100069e+21,0.000000e+00,1.190000e+20,5.445888e+18,2.642339e+38,79.0,179.917870,152.0,4.961508e+20,0.0,6.900000e+19,3.264150e+18,14.0,7.750000e+19,28.0,0.000000e+00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6068,0xf734e64e74c9c2413228006c18aa5510a95aa6a4,wallet address,1.0,2023-02-15 17:33:35,244.0,4.655518e+18,0.000000e+00,5.000000e+17,2.537903e+33,92.0,179.871215,244.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,244.0,4.655518e+18,0.000000e+00,5.000000e+17,1.907999e+16,2.537903e+33,92.0,179.871215,191.0,2.181254e+18,0.0,2.500000e+17,1.142018e+16,23.0,1.400000e+17,27.0,8.000000e+15,0
6155,0xfa89ec40699bbfd749c4eb6643dc2b22ff0e2aa6,wallet address,1.0,2023-02-15 18:04:47,1168.0,1.589276e+21,0.000000e+00,1.460000e+20,8.018246e+37,345.0,179.806019,1164.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,1168.0,1.589276e+21,0.000000e+00,1.460000e+20,1.360682e+18,8.018246e+37,345.0,179.806019,938.0,7.654181e+20,0.0,1.010000e+20,8.160108e+17,91.0,4.710000e+20,257.0,5.868557e+18,0
6202,0xfc21ff4440dd9d4fac0d115298909a372e7deed7,wallet address,1.0,2023-02-15 06:04:59,130.0,4.221676e+19,0.000000e+00,8.000000e+18,8.157024e+35,35.0,177.081829,130.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,130.0,4.221676e+19,0.000000e+00,8.000000e+18,3.247443e+17,8.157024e+35,35.0,177.081829,91.0,3.285184e+19,0.0,8.000000e+18,3.610092e+17,20.0,2.300000e+18,7.0,0.000000e+00,0
6219,0xfcb85d4139123b1ec6746d1c487a2201045b9f72,wallet address,1.0,2023-02-15 01:58:23,877.0,3.188151e+19,0.000000e+00,2.000000e+18,1.539744e+34,178.0,179.475938,873.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,877.0,3.188151e+19,0.000000e+00,2.000000e+18,3.635292e+16,1.539744e+34,178.0,179.475938,816.0,2.481428e+19,0.0,1.350000e+18,3.040966e+16,13.0,1.071174e+17,76.0,3.047000e+17,0
6277,0xfff2f0277d7899e043741eebac6553b20e0639d5,wallet address,1.0,2023-02-15 09:45:47,142.0,1.543533e+19,0.000000e+00,9.000000e+18,6.151465e+35,44.0,179.661250,142.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,142.0,1.543533e+19,0.000000e+00,9.000000e+18,1.086995e+17,6.151465e+35,44.0,179.661250,138.0,1.343533e+19,0.0,9.000000e+18,9.735746e+16,28.0,9.100000e+18,9.0,1.822000e+18,0

In [53]:
df.loc[df.days_since_last_txn == df.days_since_last_txn.max()]

,focal_addr,focal_addr_type,blacklist,last_ts,tot_txn,tot_val,min_val,max_val,sd2_val,unq_other_addr,days_diff_first_last,contract_creation,recv_txn,tot_val_recv,min_val_recv,max_val_recv,avg_val_recv,sd2_val_recv,unq_from_addr,days_diff_first_last_recv,sent_txn,tot_val_sent,min_val_sent,max_val_sent,avg_val_sent,sd2_val_sent,unq_to_addr,days_diff_first_last_sent,to_contract_txn,tot_val_to_contract,min_val_to_contract,max_val_to_contract,avg_val_to_contract,erc20_txn,sum_val_erc20,erc721_txn,sum_val_erc721,days_since_last_txn
161,0x06dd617467f941e84e4d05a8293a741ca67cdab0,wallet address,0.0,2022-08-16 04:00:04,2.0,2.000000e+16,0.000000e+00,2.000000e+16,1.000000e+32,2.0,0.020000,0.0,1.0,2.000000e+16,2.000000e+16,2.000000e+16,2.000000e+16,0.000000e+00,1.0,0.000000,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,0.000000,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,0.000000e+00,0.0,NaN,183
167,0x071ae34542450baa21a2559b846ced7a19cb0ac6,wallet address,0.0,2022-08-16 08:02:47,2.0,7.797900e+17,3.897900e+17,3.900000e+17,1.102500e+28,2.0,0.002963,0.0,1.0,3.900000e+17,3.900000e+17,3.900000e+17,3.900000e+17,0.000000e+00,1.0,0.000000,1.0,3.897900e+17,3.897900e+17,3.897900e+17,3.897900e+17,0.000000e+00,1.0,0.000000,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,183
317,0x0cc372e5d9a0783bdb3f49e39ebc5c406cd3eb27,wallet address,0.0,2022-08-16 10:47:17,1.0,5.779800e+14,5.779800e+14,5.779800e+14,0.000000e+00,1.0,0.000000,0.0,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,1.0,5.779800e+14,5.779800e+14,5.779800e+14,5.779800e+14,0.000000e+00,1.0,0.000000,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,183
877,0x2417236159891653d97786aeb112f6c5b4cb750b,wallet address,0.0,2022-08-16 09:41:12,1.0,2.018415e+16,2.018415e+16,2.018415e+16,0.000000e+00,1.0,0.000000,0.0,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,1.0,2.018415e+16,2.018415e+16,2.018415e+16,2.018415e+16,0.000000e+00,1.0,0.000000,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,183
905,0x24fd1ba897ad0425712f8e2ea73465f46241ef74,wallet address,1.0,2022-08-16 22:57:24,19.0,1.822474e+18,6.390540e+15,2.000000e+17,6.009029e+33,14.0,131.732766,19.0,7.0,1.217800e+18,1.780000e+16,2.000000e+17,1.739714e+17,4.064919e+33,4.0,104.442847,12.0,6.046735e+17,6.390540e+15,1.161000e+17,5.038946e+16,1.516382e+33,10.0,131.174306,2.0,1.885400e+16,9.073000e+15,9.781000e+15,9.427000e+15,0.0,NaN,0.0,NaN,183
1069,0x2ba23957774e7fb68ec825938c32c984d111304c,wallet address,0.0,2022-08-16 00:55:38,3.0,2.793000e+18,2.530000e+17,1.400000e+18,2.411087e+35,3.0,18.400937,0.0,1.0,1.400000e+18,1.400000e+18,1.400000e+18,1.400000e+18,0.000000e+00,1.0,0.000000,2.0,1.393000e+18,2.530000e+17,1.140000e+18,6.965000e+17,1.966923e+35,2.0,18.399780,1.0,1.140000e+18,1.140000e+18,1.140000e+18,1.140000e+18,0.0,NaN,0.0,NaN,183
1197,0x304ae81340a6f039d7c0080daea8e661eb9b36c6,wallet address,0.0,2022-08-16 06:20:44,3.0,6.000000e+15,0.000000e+00,6.000000e+15,8.000000e+30,2.0,13.180602,0.0,1.0,6.000000e+15,6.000000e+15,6.000000e+15,6.000000e+15,0.000000e+00,1.0,0.000000,2.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,13.180255,2.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,NaN,0.0,NaN,183
1221,0x3192acb015fc1c27dbd250b986c1eb87efc66070,wallet address,0.0,2022-08-16 11:37:38,1.0,5.775817e+14,5.775817e+14,5.775817e+14,0.000000e+00,1.0,0.000000,0.0,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,1.0,5.775817e+14,5.775817e+14,5.775817e+14,5.775817e+14,0.000000e+00,1.0,0.000000,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,183
1579,0x4084953b6453c9b0eaa9540d4a8a9090e966e415,wallet address,0.0,2022-08-16 01:07:16,1.0,6.017233e+14,6.017233e+14,6.017233e+14,0.000000e+00,1.0,0.000000,0.0,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,1.0,6.017233e+14,6.017233e+14,6.017233e+14,6.017233e+14,0.000000e+00,1.0,0.000000,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,183
1850,0x4a61de205ecea7dbe78ab73ba81ee8ce3197cb25,wallet address,0.0,2022-08-16 05:39:20,2.0,1.133913e+17,5.654309e+16,5.684822e+16,2.327608e+28,2.0,0.002662,0.0,1.0,5.684822e+16,5.684822e+16,5.684822e+16,5.684822e+16,0.000000e+00,1.0,0.000000,1.0,5.654309e+16,5.654309e+16,5.654309e+16,5.654309e+16,0.000000e+00,1.0,0.000000,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,183
1990,0x50bbde94863829c4544fc0e2d0dfef0138d463c9,wallet address,0.0,2022-08-16 22:36:43,3.0,9.818554e+15,0.000000e+00,6.088000e+15,6.282037e+30,3.0,0.019421,0.0,1.0,6.088000e+15,6.088000e+15,6.088000e+15,6.088000e+15,0.000000e+00,1.0,0.000000,2.0,3.730554e+15,0.000000e+00,3.730554e+15,1.865277e+15,3.479258e+30,2.0,0.005162,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,NaN,0.0,NaN,183
2319,0x5ed2dec70d5d3c09fe3521a3c72f0b4389f5fa13,wallet address,1.0,2022-08-16 04:18:12,52.0,4.308749e+18,0.000000e+00,9.900000e+17,6.236456e+34,17.0,124.219259,52.0,8.0,2.306475e+18,3.287290e+16,9.900000e+17,2.883094e+17,1.642872e+35,3.0,46.942164,44.0,2.002274e+18,0.000000e+00,9.885200e+17,4.550623e+16,3.476342e+34,16.0,124.179236,33.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.0,0.000000e+00,23.0,0.0,183
2821,0x72f7b226af39d6c5886bbd30982e6bab9f8639e7,wallet address,0.0,2022-08-16 09:59:14,1.0,8.949522e+14,8.949522e+14,8.949522e+14,0.000000e+00,1.0,0.000000,0.0,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,1.0,8.949522e+14,8.949522e+14,8.949522e+14,8.949522e+14,0.000000e+00,1.0,0.000000,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,183
3236,0x83f4ace3b3fae1be6daf73531a77944eb472b28f,wallet address,1.0,2022-08-16 01:39:00,55.0,1.254247e+18,0.000000e+00,6.300000e+17,7.462817e+33,17.0,169.464132,55.0,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,55.0,1.254247e+18,0.000000e+00,6.300000e+17,2.280449e+16,7.462817e+33,17.0,169.464132,37.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,10.0,0.000000e+00,4.0,0.0,183
3655,0x9561c2f72607e28863a93e5319f273967678ed05,wallet address,0.0,2022-08-16 08:36:05,1.0,1.241780e+15,1.241780e+15,1.241780e+15,0.000000e+00,1.0,0.000000,0.0,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,1.0,1.241780e+15,1.241780e+15,1.241780e+15,1.241780e+15,0.000000e+00,1.0,0.000000,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,183
4033,0xa3f2dea947af26d9aac01df2ba7f8edaf44b1dce,wallet address,1.0,2022-08-16 17:23:57,1.0,5.000000e+15,5.000000e+15,5.000000e+15,0.000000e+00,1.0,0.000000,1.0,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,1.0,5.000000e+15,5.000000e+15,5.000000e+15,5.000000e+15,0.000000e+00,1.0,0.000000,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,183
4264,0xad0a22f8901ccb0233a3c4be477c47d24c5201c9,wallet address,1.0,2022-08-16 13:31:17,28.0,1.086604e+19,0.000000e+00,2.324920e+18,3.297898e+35,16.0,157.468426,28.0,17.0,5.997936e+18,9.648490e+16,2.000000e+18,3.528198e+17,2.205523e+35,12.0,155.765301,11.0,4.868108e+18,0.000000e+00,2.324920e+18,4.425552e+17,4.937224e+35,4.0,154.620972,4.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.0,0.000000e+00,0.0,NaN,183
4312,0xaee2531a8f23c86f27212c6523a81df9a00e93cd,wallet address,0.0,2022-08-16 20:30:22,36.0,8.700000e+16,0.000000e+00,8.700000e+16,2.044097e+32,22.0,87.824294,0.0,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,36.0,8.700000e+16,0.000000e+00,8.700000e+16,2.416667e+15,2.044097e+32,22.0,87.824294,35.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,NaN,0.0,NaN,183
4363,0xb0f38c330ff0e9c81473695a44aab0a8b7253a0c,wallet address,0.0,2022-08-16 09:45:44,2.0,1.456850e+17,7.268500e+16,7.300000e+16,2.480625e+28,2.0,0.001516,0.0,1.0,7.300000e+16,7.300000e+16,7.300000e+16,7.300000e+16,0.000000e+00,1.0,0.000000,1.0,7.268500e+16,7.268500e+16,7.268500e+16,7.268500e+16,0.000000e+00,1.0,0.000000,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,183
4434,0xb44647e99c1db2effb139fb737869ef9ade1c1b1,wallet address,0.0,2022-08-16 23:38:58,2.0,7.836512e+15,5.329823e+14,7.303530e+15,1.146008e+31,2.0,102.897894,0.0,1.0,7.303530e+15,7.303530e+15,7.303530e+15,7.303530e+15,0.000000e+00,1.0,0.000000,1.0,5.329823e+14,5.329823e+14,5.329823e+14,5.329823e+14,0.000000e+00,1.0,0.000000,1.0,5.329823e+14,5.329823e+14,5.329823e+14,5.329823e+14,0.0,NaN,0.0,NaN,183
4751,0xc124f868b78c7a6fabc90aa03d23cbbabc0e12e5,wallet address,0.0,2022-08-16 22:46:55,1.0,5.743642e+14,5.743642e+14,5.743642e+14,0.000000e+00,1.0,0.000000,0.0,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,1.0,5.743642e+14,5.743642e+14,5.743642e+14,5.743642e+14,0.000000e+00,1.0,0.000000,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,183
4937,0xc891b3462aedd0bcf391986e8cd1ae56705b8656,wallet address,1.0,2022-08-16 12:57:39,19.0,1.682230e+18,0.000000e+00,1.000000e+18,5.921777e+34,13.0,175.763646,19.0,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,19.0,1.682230e+18,0.000000e+00,1.000000e+18,8.853842e+16,5.921777e+34,13.0,175.763646,15.0,1.542230e+18,0.000000e+00,1.000000e+18,1.028153e+17,6.0,1.000000e+18,2.0,0.0,183
5549,0xe1a0463749373f83e8bc84a7aa8cae053fae2320,wallet address,0.0,2022-08-16 17:17:03,3.0,1.748762e+17,5.856776e+14,8.812387e+16,1.665652e+33,3.0,0.018438,0.0,1.0,8.812387e+16,8.812387e+16,8.812387e+16,8.812387e+16,0.000000e+00,1.0,0.000000,2.0,8.675234e+16,5.856776e+14,8.616667e+16,4.337617e+16,1.831026e+33,2.0,0.017824,1.0,8.616667e+16,8.616667e+16,8.616667e+16,8.616667e+16,0.0,NaN,0.0,NaN,183
5753,0xea72ce516f04e759d1c1dda605801247fbd53d0e,wallet address,1.0,2022-08-16 05:57:51,203.0,1.061830e+19,0.000000e+00,4.283450e+18,9.080843e+34,82.0,20.714919,203.0,198.0,6.334854e+18,8.498080e+12,5.450060e+17,3.199421e+16,2.216661e+33,79.0,14.277257,5.0,4.283450e+18,0.000000e+00,4.283450e+18,8.566900e+17,2.935671e+36,3.0,18.214155,4.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,0.000000e+00,3.0,0.0,183
6013,0xf4df3dffa43510546d768809bca5f5e13ce6c435,wallet address,0.0,2022-08-16 18:03:37,1.0,1.759629e+16,1.759629e+16,1.759629e+16,0.000000e+00,1.0,0.000000,0.0,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,1.0,1.759629e+16,1.759629e+16,1.759629e+16,1.759629e+16,0.000000e+00,1.0,0.000000,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,183
6020,0xf528d935119bc168c45c88051cc650251587f55c,wallet address,0.0,2022-08-16 14:46:55,4.0,1.242145e+16,0.000000e+00,5.949503e+15,4.800180e+30,4.0,5.052859,0.0,1.0,4.082790e+15,4.082790e+15,4.082790e+15,4.082790e+15,0.000000e+00,1.0,0.000000,3.0,8.338663e+15,0.000000e+00,5.949503e+15,2.779554e+15,5.975635e+30,3.0,1.104606,2.0,2.389160e+15,0.000000e+00,2.389160e+15,1.194580e+15,0.0,NaN,0.0,NaN,183
6166,0xfae0659e9113baf94ab3336dbf3c7274ea2250ca,wallet address,0.0,2022-08-16 12:47:12,1.0,6.608280e+14,6.608280e+14,6.608280e+14,0.000000e+00,1.0,0.000000,0.0,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,1.0,6.608280e+14,6.608280e+14,6.608280e+14,6.608280e+14,0.000000e+00,1.0,0.000000,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,183
6196,0xfc0cdd6509b9b390b66e15b84ac3443beb72e58e,wallet address,0.0,2022-08-16 22:45:16,9.0,3.294262e+16,0.000000e+00,1.882617e+16,4.096091e+31,5.0,179.982176,0.0,2.0,1.411645e+16,2.865020e+15,1.125143e+16,7.058223e+15,1.758295e+31,2.0,0.033380,7.0,1.882617e+16,0.000000e+00,1.882617e+16,2.689453e+15,4.339896e+31,3.0,179.982176,6.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.0,0.000000e+00,0.0,NaN,183

In [55]:
df.drop('last_ts', axis=1, inplace=True)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6280 entries, 0 to 6279
Data columns (total 37 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   focal_addr                 6280 non-null   object
 1   focal_addr_type            6280 non-null   object
 2   blacklist                  6280 non-null   float64
 3   tot_txn                    6280 non-null   float64
 4   tot_val                    6280 non-null   float64
 5   min_val                    6280 non-null   float64
 6   max_val                    6280 non-null   float64
 7   sd2_val                    6280 non-null   float64
 8   unq_other_addr             6280 non-null   float64
 9   days_diff_first_last       6280 non-null   float64
 10  contract_creation          6280 non-null   float64
 11  recv_txn                   6280 non-null   float64
 12  tot_val_recv               6280 non-null   float64
 13  min_val_recv               3389 non-null   float64
 14  max_val_recv               3389 non-null   float64
 15  avg_val_recv               3389 non-null   float64
 16  sd2_val_recv               3389 non-null   float64
 17  unq_from_addr              6280 non-null   float64
 18  days_diff_first_last_recv  3389 non-null   float64
 19  sent_txn                   6280 non-null   float64
 20  tot_val_sent               6280 non-null   float64
 21  min_val_sent               5707 non-null   float64
 22  max_val_sent               5707 non-null   float64
 23  avg_val_sent               5707 non-null   float64
 24  sd2_val_sent               5707 non-null   float64
 25  unq_to_addr                6280 non-null   float64
 26  days_diff_first_last_sent  5707 non-null   float64
 27  to_contract_txn            6280 non-null   float64
 28  tot_val_to_contract        3981 non-null   float64
 29  min_val_to_contract        3981 non-null   float64
 30  max_val_to_contract        3981 non-null   float64
 31  avg_val_to_contract        3981 non-null   float64
 32  erc20_txn                  6280 non-null   float64
 33  sum_val_erc20              2499 non-null   float64
 34  erc721_txn                 6280 non-null   float64
 35  sum_val_erc721             963 non-null    float64
 36  days_since_last_txn        6280 non-null   int64
dtypes: float64(34), int64(1), object(2)
memory usage: 1.8+ MB

In [75]:
# Check for duplicates
duplicates = df[df.duplicated()]
duplicates

Empty DataFrame
Columns: [focal_addr, focal_addr_type, blacklist, tot_txn, tot_val, min_val, max_val, sd2_val, unq_other_addr, days_diff_first_last, contract_creation, recv_txn, tot_val_recv, min_val_recv, max_val_recv, avg_val_recv, sd2_val_recv, unq_from_addr, days_diff_first_last_recv, sent_txn, tot_val_sent, min_val_sent, max_val_sent, avg_val_sent, sd2_val_sent, unq_to_addr, days_diff_first_last_sent, to_contract_txn, tot_val_to_contract, min_val_to_contract, max_val_to_contract, avg_val_to_contract, erc20_txn, sum_val_erc20, erc721_txn, sum_val_erc721, days_since_last_txn]
Index: []

In [57]:
# Check for Nulls
df.isnull().sum()

focal_addr                      0
focal_addr_type                 0
blacklist                       0
tot_txn                         0
tot_val                         0
min_val                         0
max_val                         0
sd2_val                         0
unq_other_addr                  0
days_diff_first_last            0
contract_creation               0
recv_txn                        0
tot_val_recv                    0
min_val_recv                 2891
max_val_recv                 2891
avg_val_recv                 2891
sd2_val_recv                 2891
unq_from_addr                   0
days_diff_first_last_recv    2891
sent_txn                        0
tot_val_sent                    0
min_val_sent                  573
max_val_sent                  573
avg_val_sent                  573
sd2_val_sent                  573
unq_to_addr                     0
days_diff_first_last_sent     573
to_contract_txn                 0
tot_val_to_contract          2299
min_val_to_contract          2299
max_val_to_contract          2299
avg_val_to_contract          2299
erc20_txn                       0
sum_val_erc20                3781
erc721_txn                      0
sum_val_erc721               5317
days_since_last_txn             0
dtype: int64

In [58]:
# Check for Nan values
df.isna().sum()

focal_addr                      0
focal_addr_type                 0
blacklist                       0
tot_txn                         0
tot_val                         0
min_val                         0
max_val                         0
sd2_val                         0
unq_other_addr                  0
days_diff_first_last            0
contract_creation               0
recv_txn                        0
tot_val_recv                    0
min_val_recv                 2891
max_val_recv                 2891
avg_val_recv                 2891
sd2_val_recv                 2891
unq_from_addr                   0
days_diff_first_last_recv    2891
sent_txn                        0
tot_val_sent                    0
min_val_sent                  573
max_val_sent                  573
avg_val_sent                  573
sd2_val_sent                  573
unq_to_addr                     0
days_diff_first_last_sent     573
to_contract_txn                 0
tot_val_to_contract          2299
min_val_to_contract          2299
max_val_to_contract          2299
avg_val_to_contract          2299
erc20_txn                       0
sum_val_erc20                3781
erc721_txn                      0
sum_val_erc721               5317
days_since_last_txn             0
dtype: int64

In [59]:
df.blacklist.value_counts()

0.0    3978
1.0    2302
Name: blacklist, dtype: int64

In [60]:
df.focal_addr_type.value_counts()

wallet address      5993
contract address     287
Name: focal_addr_type, dtype: int64

In [61]:
df.head(2)

,focal_addr,focal_addr_type,blacklist,tot_txn,tot_val,min_val,max_val,sd2_val,unq_other_addr,days_diff_first_last,contract_creation,recv_txn,tot_val_recv,min_val_recv,max_val_recv,avg_val_recv,sd2_val_recv,unq_from_addr,days_diff_first_last_recv,sent_txn,tot_val_sent,min_val_sent,max_val_sent,avg_val_sent,sd2_val_sent,unq_to_addr,days_diff_first_last_sent,to_contract_txn,tot_val_to_contract,min_val_to_contract,max_val_to_contract,avg_val_to_contract,erc20_txn,sum_val_erc20,erc721_txn,sum_val_erc721,days_since_last_txn
0,0x00000002de4e35b0838fe97e09bb26317c2e570c,contract address,0.0,402.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,1.0,70.540139,0.0,402.0,0.0,0.0,0.0,0.0,0.0,1.0,70.540139,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,17
1,0x0000000506063a51c6ce59906d8c40f7d7fe92a7,wallet address,1.0,16.0,1.843963e+19,0.0,1.800000e+19,1.892915e+37,13.0,153.244306,16.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,16.0,1.843963e+19,0.0,1.800000e+19,1.152477e+18,1.892915e+37,13.0,153.244306,10.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,NaN,0

### Setting 0 to all Nan values in  the fields related to Received transactions if recv_txn is zero

In [62]:
recv_na_cols = ['min_val_recv', 'max_val_recv', 'avg_val_recv', 'sd2_val_recv', 'days_diff_first_last_recv']
df.loc[df['recv_txn'] == 0, recv_na_cols] = df.loc[df['recv_txn'] == 0,recv_na_cols].fillna(0)

In [16]:
df.head()

,focal_addr,focal_addr_type,blacklist,last_ts,tot_txn,tot_val,min_val,max_val,sd2_val,unq_other_addr,days_diff_first_last,contract_creation,recv_txn,tot_val_recv,min_val_recv,max_val_recv,avg_val_recv,sd2_val_recv,unq_from_addr,days_diff_first_last_recv,sent_txn,tot_val_sent,min_val_sent,max_val_sent,avg_val_sent,sd2_val_sent,unq_to_addr,days_diff_first_last_sent,to_contract_txn,tot_val_to_contract,min_val_to_contract,max_val_to_contract,avg_val_to_contract,erc20_txn,sum_val_erc20,erc721_txn,sum_val_erc721
0,0x00000002de4e35b0838fe97e09bb26317c2e570c,contract address,0.0,2023-01-29 21:43:23,402.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,70.540139,0.0,402.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,70.540139,0.0,0.000000e+00,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,0x0000000506063a51c6ce59906d8c40f7d7fe92a7,wallet address,1.0,2023-02-15 15:53:59,16.0,1.843963e+19,0.000000e+00,1.800000e+19,1.892915e+37,13.0,153.244306,16.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,NaN,16.0,1.843963e+19,0.000000e+00,1.800000e+19,1.152477e+18,1.892915e+37,13.0,153.244306,10.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,3.0,0.000000e+00,0.0,NaN
2,0x0000098a312e1244f313f83cac319603a97f4582,wallet address,1.0,2023-02-08 12:19:59,8792.0,1.500201e+19,0.000000e+00,1.000000e+18,1.703185e+33,1486.0,103.834028,8792.0,17.0,1.500000e+19,1.000000e+10,1.000000e+18,8.823529e+17,1.038062e+35,3.0,70.376528,8775.0,2.010000e+15,0.000000e+00,1.000000e+15,2.290598e+11,2.278792e+26,1483.0,103.834028,8493.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,1356.0,0.000000e+00,4225.0,0.000000e+00
3,0x000677bbab0fea85506f5f63806d331c9c2df1ac,wallet address,0.0,2022-08-21 09:26:43,1.0,7.287733e+14,7.287733e+14,7.287733e+14,0.000000e+00,1.0,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,NaN,1.0,7.287733e+14,7.287733e+14,7.287733e+14,7.287733e+14,0.000000e+00,1.0,0.000000,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,0x000f4432a40560bbff1b581a8b7aded8dab80026,wallet address,1.0,2023-02-15 01:53:11,247.0,4.243310e+19,0.000000e+00,8.200000e+18,5.954650e+35,91.0,179.527037,247.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,NaN,247.0,4.243310e+19,0.000000e+00,8.200000e+18,1.717939e+17,5.954650e+35,91.0,179.527037,215.0,2.880170e+19,0.0,8.200000e+18,1.339614e+17,30.0,1.045000e+19,17.0,5.500000e+17

### Setting 0 to all Nan values in  the fields related to Sent transactions if sent_txn is zero

In [66]:
sent_na_cols = ['min_val_sent', 'max_val_sent', 'avg_val_sent', 'sd2_val_sent', 'days_diff_first_last_sent']
df.loc[df['sent_txn'] == 0, sent_na_cols] = df.loc[df['sent_txn'] == 0, sent_na_cols].fillna(0)

### Setting 0 to all Nan values in  the fields related to Contract transactions if to_contract_txn is zero

In [67]:
contract_na_cols = ['tot_val_to_contract','min_val_to_contract', 'max_val_to_contract', 'avg_val_to_contract']
df.loc[df['to_contract_txn'] == 0, contract_na_cols] = df.loc[df['to_contract_txn'] == 0, contract_na_cols].fillna(0)

### Setting 0 to all Nan values in  the fields related to ERC20 transactions if erc20_txn is zero

In [68]:
df.loc[df['erc20_txn'] == 0, 'sum_val_erc20'] = df.loc[df['erc20_txn'] == 0, 'sum_val_erc20'].fillna(0)

### Setting 0 to all Nan values in  the fields related to ERC721 transactions if erc721_txn is zero

In [69]:
df.loc[df['erc721_txn'] == 0, 'sum_val_erc721'] = df.loc[df['erc721_txn'] == 0, 'sum_val_erc721'].fillna(0)

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6280 entries, 0 to 6279
Data columns (total 37 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   focal_addr                 6280 non-null   object
 1   focal_addr_type            6280 non-null   object
 2   blacklist                  6280 non-null   float64
 3   tot_txn                    6280 non-null   float64
 4   tot_val                    6280 non-null   float64
 5   min_val                    6280 non-null   float64
 6   max_val                    6280 non-null   float64
 7   sd2_val                    6280 non-null   float64
 8   unq_other_addr             6280 non-null   float64
 9   days_diff_first_last       6280 non-null   float64
 10  contract_creation          6280 non-null   float64
 11  recv_txn                   6280 non-null   float64
 12  tot_val_recv               6280 non-null   float64
 13  min_val_recv               6280 non-null   float64
 14  max_val_recv               6280 non-null   float64
 15  avg_val_recv               6280 non-null   float64
 16  sd2_val_recv               6280 non-null   float64
 17  unq_from_addr              6280 non-null   float64
 18  days_diff_first_last_recv  6280 non-null   float64
 19  sent_txn                   6280 non-null   float64
 20  tot_val_sent               6280 non-null   float64
 21  min_val_sent               6280 non-null   float64
 22  max_val_sent               6280 non-null   float64
 23  avg_val_sent               6280 non-null   float64
 24  sd2_val_sent               6280 non-null   float64
 25  unq_to_addr                6280 non-null   float64
 26  days_diff_first_last_sent  6280 non-null   float64
 27  to_contract_txn            6280 non-null   float64
 28  tot_val_to_contract        6280 non-null   float64
 29  min_val_to_contract        6280 non-null   float64
 30  max_val_to_contract        6280 non-null   float64
 31  avg_val_to_contract        6280 non-null   float64
 32  erc20_txn                  6280 non-null   float64
 33  sum_val_erc20              6280 non-null   float64
 34  erc721_txn                 6280 non-null   float64
 35  sum_val_erc721             6280 non-null   float64
 36  days_since_last_txn        6280 non-null   int64
dtypes: float64(34), int64(1), object(2)
memory usage: 1.8+ MB

In [71]:
df.isna().sum()

focal_addr                   0
focal_addr_type              0
blacklist                    0
tot_txn                      0
tot_val                      0
min_val                      0
max_val                      0
sd2_val                      0
unq_other_addr               0
days_diff_first_last         0
contract_creation            0
recv_txn                     0
tot_val_recv                 0
min_val_recv                 0
max_val_recv                 0
avg_val_recv                 0
sd2_val_recv                 0
unq_from_addr                0
days_diff_first_last_recv    0
sent_txn                     0
tot_val_sent                 0
min_val_sent                 0
max_val_sent                 0
avg_val_sent                 0
sd2_val_sent                 0
unq_to_addr                  0
days_diff_first_last_sent    0
to_contract_txn              0
tot_val_to_contract          0
min_val_to_contract          0
max_val_to_contract          0
avg_val_to_contract          0
erc20_txn                    0
sum_val_erc20                0
erc721_txn                   0
sum_val_erc721               0
days_since_last_txn          0
dtype: int64

In [72]:
df.isnull().sum()

focal_addr                   0
focal_addr_type              0
blacklist                    0
tot_txn                      0
tot_val                      0
min_val                      0
max_val                      0
sd2_val                      0
unq_other_addr               0
days_diff_first_last         0
contract_creation            0
recv_txn                     0
tot_val_recv                 0
min_val_recv                 0
max_val_recv                 0
avg_val_recv                 0
sd2_val_recv                 0
unq_from_addr                0
days_diff_first_last_recv    0
sent_txn                     0
tot_val_sent                 0
min_val_sent                 0
max_val_sent                 0
avg_val_sent                 0
sd2_val_sent                 0
unq_to_addr                  0
days_diff_first_last_sent    0
to_contract_txn              0
tot_val_to_contract          0
min_val_to_contract          0
max_val_to_contract          0
avg_val_to_contract          0
erc20_txn                    0
sum_val_erc20                0
erc721_txn                   0
sum_val_erc721               0
days_since_last_txn          0
dtype: int64

In [73]:
df.to_excel('cleaned_data.xlsx')